workspace:
  base: /go
  path: src/github.com/koala2012/HelloWorld

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
    docker-package:
      image: docker:dind
      commands:
        - docker version
