workspace:
  base: /go
  path: src/github.com/koala2012/HelloWorld

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
    docker-package:
      image: docker:17.05.0-ce-dind
      environment:
        - DOCKER_HOST=tcp://docker:2375
      commands:
        - sleep 5
        - docker ps
        
services:
  docker:
    image: docker:17.05.0-ce-dind
    privileged: true
