workspace:
  base: /go
  path: src/github.com/koala2012/HelloWorld

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
    docker-package:
      image: docker:dind
      volumes:
        - /usr/bin/docker:/usr/bin/docker
        - /var/run/docker.sock:/var/run/docker.sock
      commands:
        - docker info
